-- Intentionally left blank.
--
-- The repository no longer preserves historical finalized-row repair semantics.
-- Keep migration version 12 present so databases that already recorded it remain
-- compatible with the compiled migration chain.
